# Generated by Django 5.1.3 on 2024-12-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stdstruc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Compon', models.CharField(max_length=200)),
                ('Componlink', models.CharField(max_length=200)),
            ],
        ),
    ]
