# Generated by Django 5.1.3 on 2024-12-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeamEN100561',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=10)),
                ('Secarea', models.CharField(max_length=10)),
                ('a', models.CharField(max_length=10)),
                ('b', models.CharField(max_length=10)),
                ('t', models.CharField(max_length=10)),
                ('r', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BeamEN10365',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proftype', models.CharField(max_length=10)),
                ('Size', models.CharField(max_length=10)),
                ('h', models.CharField(max_length=10)),
                ('b', models.CharField(max_length=10)),
                ('s', models.CharField(max_length=10)),
                ('t', models.CharField(max_length=10)),
                ('Secarea', models.CharField(max_length=10)),
            ],
        ),
    ]
