# Generated by Django 5.1.3 on 2024-12-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamen100561',
            name='Size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='beamen10365',
            name='Size',
            field=models.CharField(max_length=20),
        ),
    ]
